"""Added Role to User table

Revision ID: fef436b63856
Revises: 2e46f6b23836
Create Date: 2025-06-22 16:26:55.406029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from src.database.models import Roles


# revision identifiers, used by Alembic.
revision: str = "fef436b63856"
down_revision: Union[str, None] = "2e46f6b23836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sqlalchemy_utils.types.choice.ChoiceType(choices=Roles, impl=sa.String()),
            nullable=False,
            server_default=f"{Roles.USER.value}",
        ),
    )
    op.drop_column("users", "is_staff")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_staff",
            sa.BOOLEAN(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
